/*
Eco's Questions - A universal JS implementation

Puts a random string inside any div tag with the ID "randomString."
Randomly selects a new one whenever a mouse click is detected anywhere on the page.

Questions come from ongoing discussions and experiences with friends mostly in VRChat.

Array of questions last updated: 27 April 2025 

*/

//Big array of questions 
const strings = [
//public string[] textPrompts = {  //Udon placeholder for VRChat world, Eco's Alcove.
	// Old questions
	"Are you afraid of getting older? Why?",
	"Describe the career of your ideal partner.",
	"Describe the most dangerous situation you have ever been in.",
	"Describe your perfect weekend getaway.",
	"Do you think you act your age, and why?",
	"Do you want to have a child one day? Why?",
	"Have you ever had your fortune told? How was it?",
	"Head, Heart, Gut - which one do you listen to the most?",
	"How much money would you need to feel financially secure?",
	"How spiritual are you, from 1 to 10?",
	"How would you like to live in old age?",
	"If you could have a superpower, what would it be and why?",
	"If you could have another home anywhere in the world, where would it be?",
	"If you could have dinner with a fictional character, who would it be and why?",
	"If you could invite any three people, dead or alive, to a dinner party, who would they be and why?",
	"If you could travel back in time, which historical event would you like to witness?",
	"If you had a time machine, which mistake would you like to return to and fix?",
	"Is there any stranger you met long ago that you still think about to this day?",
	"Is there anything about you that your parents never understand?",
	"What advice did you receive as a child that you still follow today?",
	"What are three things you can reach right now without getting up?",
	"What are you looking forward to?",
	"What could you have done with a bit more luck and encouragement?",
	"What do you love and hate most about the world?",
	"What do you normally do when you are pondering a difficult decision?",
	"What do you spend the most money on?",
	"What do you think about the most when daydreaming",
	"What do you wear when you want to look attractive?",
	"What is a guilty pleasure you enjoy but rarely admit to?",
	"What is a meal that others enjoy eating, and that you are good at cooking?",
	"What is a personal goal you have right now?",
	"What is a quote or mantra you live by?",
	"What is a random act of kindness you have experienced or witnessed?",
	"What is one small thing that makes you smile every day?",
	"What is one thing someone can be sure of when hanging out with you?",
	"What is the best memory you have had inside VRChat?",
	"What is the most embarrassingly funny thing you have ever done?",
	"What is the most interesting or bizarre coincidence ever experienced?",
	"What is the most unusual or unexpected place you've ever visited?",
	"What is the most valuable lesson you've learned from a difficult situation?",
	"What is your favorite comfort food?",
	"What is your favorite family tradition or holiday celebration?",
	"What is your favorite memory with a close friend or family member?",
	"What is your favorite thing about the city or town you live in?",
	"What is your favorite type of weather and why?",
	"What is your favorite way to relax after a long day?",
	"What new skill would you like to learn?",
	"What was the last book or movie that made you cry?",
	"What was the last thing that made you genuinely laugh out loud?",
	"What was your most memorable dream or nightmare?",
	"What was your stupidest financial decision of all time?",
	"What would be the ideal place to go on a date?",
	"What's something you used to believe but have since changed your mind about?",
	"When was the last time you did something for the first time?",
	"When was the last time you said \"I love you?\"",
	"Which of your friends do you envy the most?",
	"Which part of your body do you like the most?",
	"Who are the two people you've been thinking about a lot lately?",
	"Who do you genuinely want the best for?",
	"Who do you go to for advice?",
	"Who is your all-time favorite co-worker, and what do you like about that person?",
	"Who is your youngest and oldest friend?",
	"Is romance something that resonates with you? In what way?",
	"Are you in a relationship? What's the reason behind your relationship status?",
	"In three words, describe the last person who answered a question.",
	"If given the option, would you choose to live forever? Why or why not?",
	"How does your current best friend differ from your childhood best friend?",
	"If you could become an expert in any subject, what would it be and why?",
	"Name three people you'd choose for a road trip and the destination you'd pick.",
	"If you could instantly master a new language, which one would you choose and why?",
	"Is there a particular activity you wish you had a friend to do it with?",
	"What is something you are no longer afraid of?",
	"Were you a \"problem child\" growing up?",
	"In three words, describe your personality.",
	"What skills or talents do you excel at?",
	"What are your current top three favorite conversation topics?",
	"What makes you highly anxious in public?",
	"What activities did you love doing as a child?",
	"What do you believe most older people excel at compared to the younger generation?",
	"When going out to eat/drink, what is your usual order?",
	"If given the ideal chance, what would you like to tell your parents?",
	"What hobby or interest have you not pursued yet but wish to?",
	"Where do you go to recharge your life battery?",
	"When you are feeling down, what music might you listen to?",
	"What significant experience from the last two years changed your life?",
	"What is the best compliment you've ever been given?",
	"What is the most challenging obstacle you've successfully overcome?",
	"What is the  best lesson you've taken away from a mistake in a relationship?",
	"What street in your town do you favor the most, and how would you describe it?",
	"What role do you usually take when working on a team project?",
	"What type of person do you typically attract or find falling for you?",
	"What recent action have you done that made someone genuinely happy?",
	"Which toys were your favorites as a child, and what are your favorite ones now?",
	"When was the last time you comforted someone?",
	"Which decade do you find the most enjoyable, and why?",

	//ai-gen'd
	"Are you a morning person or a night owl, and why?",
	"If you could attend any major event in history, what would it be?",
	"If you could be a character in any fictional universe, which one would you choose?",
	"If you could be an expert in any field overnight, what would it be?",
	"If you could design your own dream world, what would it look like?",
	"If you could eliminate one thing from your daily routine, what would it be?",
	"If you could have a conversation with any fictional character, who would it be?",
	"If you could have a conversation with your future self, what would you ask?",
	"If you could have a conversation with your pet, what would you ask?",
	"If you could have any animal as a pet, mythical or real, what would it be?",
	"If you could have any type of food delivered to you right now, what would it be?",
	"If you could invent a new holiday, what would it celebrate?",
	"If you could learn any instrument effortlessly, which one would it be?",
	"If you could live in any fictional world, which one would it be?",
	"If you could switch lives with someone for a day, who would it be and why?",
	"If you could time travel to your own future, what age would you visit and why?",
	"What's the most beautiful natural landscape you've ever seen?",
	"What's the most beautiful place you've ever visited?",
	"What's the most memorable piece of advice you've ever received?",
	"What is your most treasured possession and why?",
	"What's the most unusual talent or skill you've come across in someone else?",
	"What's your favorite outdoor activity or sport?",
	"What's your favorite season and why?",
	"Name something about yourself that you wish others noticed more?",
	"What's your favorite way to spend a lazy day?",
	"What's your favorite way to stay active or fit?",
	"What's your favorite type of music, and why does it resonate with you?",
	"What's your spirit animal and why?",

	//googl'd
	"What qualities do you value most in a friend?",
	"Do you worry about your future, or take things as they come?",
	"Do you consider yourself an introvert or extrovert?",
	"How do you prefer to cook your eggs?",
	"If you could be any animal or creature, which one would you be?",
	"What is the best prank you’ve ever pulled on someone?",
	"Who do you feel the safest around?",
	"What are you putting off right now?",
	"You just won $10000. what are you going to do with the money?",
	"How many pillows do you sleep with?",
	"Are you a clean or messy person?",
	"What three items would you take with you on a deserted island?",
	"If you had a warning label, what would yours say?",
	"What’s something that most people don’t know about you?",
	"What’s something you could talk about for 30 minutes with no preparation?",
	"How do you think your closest friends would describe you? Do you agree?",
	"What’s an activity that instantly calms you?",

	//Random CQR QOTD Discord
	"What incredibly common thing have you never done?",
	"What's the longest trip you've been on?",
	"What catchy jingle or bit of advertising has stuck with you?",
	"What natural landmark would you like to see someday?",
	"What takes a lot of time but is totally worth it?",
	"What's your favorite kind of dessert?",
	"What is the farthest you have ever been from where you were born?",
	"What's something inexpensive that holds a lot of sentimental value to you?",
	"What do you get every time you go grocery shopping?",
	"What's your favorite accessory or clothing item?",
	"What is something you are utterly obsessed with at the moment?",
	"What is your computer or phone wallpaper?",
	"What word or saying from the past do you think needs to make a comeback?",
	"If the internet suddenly stopped existing, what would you do with the time you used to spend on it?",
	"If you could have an endless candle that smelled like anything, what fragrance would you want it to be?",
	"If you didn't have to sleep, what would you do with the extra time?",
	"What age do you wish you could permanently be?",
	"When things break, do you prefer to fix them or replace them?",
	"What improved your life quality so much, you wish you did it sooner?",
	"What's the best food for a food fight?",
	"What's the weather like today where you are?",
	"When people come to you for help, what do they usually want help with?",
	"What's the story behind your username?",
	"What kinds of things do you like to cook or are good at cooking?",
	
	"How would society and daily routines change if sleep wasn't necessary?",
	"Where or what is your happy place?",
	"What would happen if everyone could remember their dreams in vivid detail?",
	"If you had to choose an era to live in for a year, which would it be and why?",
	"What does your idea of a perfect day look like?",
	"If you could decide the theme for the next decade, what would it be and why?",
	"What is your favorite accessory/jewelry piece that you own?",
	"Would you rather lounge by the pool or on the beach?",
	"What is/was your favorite stuffed animal like? Tell us all about them.",
	"What things or people make you the happiest?",
	"What do you think is the most amazing thing about the universe?",
	"What are some little known relationship GREEN flags?",
	"What book or movie profoundly changed your perspective on life? What impact did it have on you?",
	"What was the best vacation you've ever been on?",
	"What is very hard to get and very easy to lose?",
	"What are your favourite activities to do with others?",
	"What time of day do you work best?",

	//Random get to know yo friends 3k worlds
	"What does 'beauty' mean to you?",
	"When was the last time you cried with laughter?",
	"What is your relationship with technology?",
	"Do you have any hidden talents?",
	"On a scale of 1 to 10, how unlucky are you?",
	"How many friend groups do you have?",
	"On a scale from 1 to 10, how often do you lie?",
	"Who do you admire in your friend group?",
	"Do you prefer sunrises OR sunsets? Why?",
	"What is something you can talk about for an hour without preparation?",
	"What are three really small victories you had in the last few days that you're proud of?",
	"How many pillows do you sleep with?",
	"How do you feel about putting pineapple on pizza?",
	"Have you ever visited the dark web?",
	"Do you feel more like a leader or a follower?",
	"What is your greatest strength?",
	"What are your top three long-term goals?",
	"What makes you feel accomplished?",
	"On a scale from 1 to 10, how social are you?",
	"How do you respond in an emergency?",
	"On a scale from 1 to 10, how often do you drink water?",
	"What is your favorite school subject?",
	"Have you ever purchased a house?",
	"How imaginative are you?",
	"What makes you feel safe?",
	"How did you meet your best friend?",
	"If the average human lifespan was 40 years, how would you live your life differently?",
	"Which website should come back from the dead?",
	"On a scale of 1 to 10, how tough are you?",
	"What is your all-time favorite way to sleep?",
	"Describe your perfect day.",
	"Do you like hugs, or do you avoid them?",
	"Are you happy?",
	"What is your favorite orange item?",
	"Are you dyslexic?",
	"Are you ambidextrous, right- or left-handed?",
	"Are you an angel or a demon in disguise? ",
	"What caused you to feel nostalgic recently?",
	"Have you ever been on TV?",
	"Are you more of an explorer or a homebody?",
	"In your friend group, who gets in the most trouble?",
	"If you could delete one website, which one would it be?",
	"If you had a pet parrot, what would you teach it to say?",
	"Would you rather tame a dragon or a dinosaur?",
	"If your friends were food, who would be what?",
	"Do you know a lot about geography? Where is Woolloomooloo?",
	"What can people learn from animals?",
	"What tickles your curiosity?",
	"Out of all of your friends, who do you have an unbreakable bond with?",
	"Do you enjoy trying out new foods? What was the most recent new food you tried?",
	"Name an ice cream flavor that represents your personality.",
	"When you answer the phone, what do you say?",
	"What animal makes your heart melt the moment you see it?",
	"What website should everyone check out?",
	"On a scale from 1 to 10, how good at cooking are you?",
	"Do you know any riddles? If so, share one.",
	"Do you have a running joke in your friend group?",
	"Is the glass half empty or half full?",
	"On a scale from 1 to 10, how good are you at saving money?",
	"If you could eat in VR, what would you try first?",
	"How ticklish are you?",
	"Do you experience a phantom sense in VR?",
	"What do you daydream about?",
	"Name your home world and why is it your home world?",
	"Are you more into one's looks or brains?",
	"If you were an action figure, what accessories would you be sold with?",
	"What is your favorite thing about Europe?",
	"How many hats do you own?",
	"When you are upset, ill, or enraged, how do you prefer to be comforted?",
	"What was your first video game console?",
	"How would you like to be remembered by a stranger?",
	"If you could live in any alternate universe, where would you go?",
	"What is the weirdest fact you know?",
	"If you could tell your younger self anything, what would it be?",
	"What is your biggest secret indulgence?",
	"What are three things you are thankful for?",
	"When you see a puddle on the ground, do you walk around it, or jump in it?",

	//From discord friends
	"Do you prefer playing games alone, with friends, or with strangers?",
	"What is the weirdest food or food combination that you've eaten?",
	"If you had intro/theme music, what song would it be?",
	"Whose a YouTuber that you watched when you were younger but grew out of watching?",
	"What game would you like to get a sequel?",
	"What is an online game that was discontinued or shut down you'd want to come back?",
	"What was your first video gaming platform and what was your game of choice?",
	"What is your favorite dinosaur and why?",
	"What is the cheesiest pickup line you used on someone personally?",
	"What is something you did today?",
	"What is something you are STILL salty about?",
	"What's one thing you're looking forward to today?",
	"What about you now would most impress your younger self?",
	"Do you have any pets? If not, do you want any?",
	"Do you have any tattoos? If not, do you want any?",
	"What is the most interesting thing you see on your way to school or work?",
	"What would society look like if everyone could teleport anywhere at will?",
	"What is your ideal snack item of choice?",
	"What is your favorite type of stuffed animal (texture, animal, brand, etc.)?",
	"If you could place any object on another planet, purely to confuse NASA scientists, what would it be?",
	"Whats your favorite dragon from media?",

	//Thad vrchat worlds
	"A tiny version of you appears and starts narrating your life out loud. Do you get along, or does tiny-you need to chill?",
	"Are eyebrows considered facial hair?",
	"Are farts funny?",
	"Are you a tea or coffee person, or something else entirely?",
	"Are you an early bird or a night owl?",
	"Are you more of a \"just one more episode\" person or a \"bed by 9\" type?",
	"Bread, rice, noodles, or potatoes?",
	"Can a routine be freeing instead of limiting?",
	"Can doing nothing ever be productive?",
	"Can you enjoy \"bad weather\"?",
	"Can you plan to be spontaneous?",
	"Can you teach a sentence in a different language?",
	"Can you tell a scary story?",
	"Could you share one embarrassing story?",
	"Did you ever have dreams that makes you feel embarrassed for having?",
	"Did you have a dream in the past that you gave up on?",
	"Do we notice beauty, or do we create it?",
	"Do you believe in love at first sight? Has it ever happened to you?",
	"Do you believe people can truly change?",
	"Do you choose your habits, or do your habits choose you?",
	"Do you fall more for how someone treats you or how they see you? ",
	"Do you feel like the protagonist or a side character in your own life?",
	"Do you have a \"dramatic overreaction\" mode, and if so, when does it make an appearance?",
	"Do you have a framed picture somewhere? What does it show?",
	"Do you have a signature move, phrase, or action? Maybe even one you only do in private?",
	"Do you have an ultimate \"this song is me\" kind of thing?",
	"Do you have any (good or bad) pickup line?",
	"Do you do any little rituals before you go to bed?",
	"Do you have any unusual sleeping habits?",
	"Do you have any useless skills?",
	"Do you have something that helps you relax that most people wouldn't expect?",
	"Do you need a lot of time for yourself or do you prefer being in company most of the time?",
	"Do you talk to yourself, your plants, your pets - or all of them?",
	"Do you tend to be early, right on time, or fashionably late?",
	"Do you tend to run toward things or away from them?",
	"Do you tend to switch interests now and then or do you stay with things for a long time?",
	"Do you think limitations are necessary for creativity? Could people still be creative if everything was possible with ease?",
	"Do you think you're more yourself when you're alone or around others?",
	"Does where you're from shape who you are—or just how you start?",
	"For food, do you save the best for last, or do you go for the best first?",
	"Give someone else a compliment.",
	"Have you ever felt a connection that didn't make logical sense, but felt right anyway?",
	"Have you ever had an imaginary friend?",
	"Have you ever tried to impress someone and failed miserably?",
	"Having a tail in real life - yay or nay?",
	"How could one measure loneliness?",
	"How do you usually show someone you're into them? Do you drop hints?",
	"How many holes does a straw have?",
	"How many more years do you give humanity?",
	"How would you describe VRChat to someone who never heard about it?",
	"If \"authentic\" becomes a trend, does it stop being authentic?",
	"If a tree falls in a forest and nobody films it, is it still content?",
	"If all humans disappeared tomorrow, what do you think the world would look like in a thousand years?",
	"If animals could talk, what would be the first question you'd ask them? What do you think they'd ask",
	"If animals could talk, which one do you think would be the biggest drama queen?",
	"If life was an Anime, what kind of character would you be?",
	"If real life had a skill system, which attribute would you spend most of your points on?",
	"If someone really wanted to understand you, what's a question they should ask?",
	"If someone wanted to really get close to you, what would they need to understand first?",
	"If the world ended tomorrow, how would you spend your last day?",
	"If time flies when you're having fun, do bored people live longer?",
	"If time were a physical substance, how would you use it? Would you hoard it, spend it freely, or give it away?",
	"If you became a supervillain, what kind of evil plan would you have for the world?",
	"If you clean out the dirt from a vacuum cleaner does that make you a vacuum cleaner?",
	"If you could be any other living creature for a day, what would you choose?",
	"If you could change one thing about society, what would it be?",
	"If you could change one thing in your past, what would it be? ",
	"If you could create one universal law that everyone had to follow, what would it be?",
	"If you could design the perfect society, what would its core principles be? What would it value?",
	"If you could design your dream day, no limits, what's a weird little detail that would have to be in it?",
	"If you could have a conversation with your past self, what advice would you give them, and what would you want to know?",
	"If you could hear everyone's thoughts for one day when they think about you - would you do it?",
	"If you could instantly learn one thing, what would you want to learn?",
	"If you could live in any fictional universe, which one would you choose?",
	"If you could live one year of your life completely free from consequences, how would you spend it?",
	"If you could only ask one question to someone you may have an interest in, what would you ask?",
	"If you could only communicate through animal sounds, what would be your most used sound?",
	"If you could only experience one emotion for the rest of your life, which would it be?",
	"If you could only remember one thing from your past life up until now, what would you want it to be?",
	"If cars had to look like cute animal-shaped vehicles from now on, which animal would you be cruising in?",
	"If you could pick one question that is always assured to get an honest answer, what would you pick?",
	"If you could pick one superpower for yourself, what would you pick?",
	"If you could relive one day without changing anything (just to feel it again), what day would it be?",
	"If you could rewrite any chapter of your life, which one would it be?",
	"If you enjoy wasting time, is it really wasted?",
	"If you had a one way time travel ticket, where would you travel?",
	"If you had a tiny fictional creature sidekick that followed you around, what would it be and what's its vibe?",
	"If you had the ability to always know the future, would you want to know it?",
	"If you had to be reborn somewhere else on this earth, where would you choose?",
	"If you had to describe your personality as a weather pattern, what would it be?",
	"If you had to describe your wardrobe with a single word, what would you choose?",
	"If you had to eat one food for the rest of your life, what would you choose?",
	"If you had to enter a talent show with zero prep, what would you do?",
	"If you had to fight a clone of yourself but they were slightly better at everything, what would be your strategy?",
	"If you had to live the rest of your life in the setting of the last show or movie you watched, how screwed are you?",
	"If you had to pick a favorite kind of weather, what would it be and why?",
	"If you had to swap lives with someone for a week, real or fictional, who would you pick?",
	"If you had to wear one Halloween costume every day for a year, what would you choose?",
	"If you had to wear one outfit for the rest of your life - what would you pick?",
	"If you were a ghost, which object would you haunt?",
	"If you were an NPC with a quest in a video game, what would you like to make the player do for you?",
	"If you were given the power to change one fundamental law of physics, which would you alter?",
	"If you were reborn in another world as an object, what would you be?",
	"If your favorite fictional character showed up and said \"let's hang out\", what would you want to do together?",
	"If your favorite memory were a postcard, what would the picture on it be?",
	"If your future self could send you a one sentence long message, what do you hope it says?",
	"If your life had a genre or theme, what would it be?",
	"If your life was secretly a simulation, what's something you'd like to say to the creator?",
	"If your life were a board game, what would be a weird rule in it?",
	"If your personality had to be expressed through a spice, which one are you?",
	"If your personality were a cozy little shop, what would you sell?",
	"If your shadow had a personality, would it get along with you?",
	"Imagine you could see stats on people (for example, lies per day), what kind of stats would you like to see?",
	"In what state of matter does pudding exist?",
	"Including imaginary jobs that don't exist; what would be your dream job?",
	"Is cereal a soup? What about yourself if you take a bath?",
	"Is comfort the opposite of growth, or part of it?",
	"Is happiness something you find or something you create?",
	"Is it better to be kind or to be honest?",
	"Is it possible to feel nostalgic for something that never happened?",
	"Is it sometimes better to tell a lie?",
	"Is losing the track of time the best way to know it was well spent?",
	"Is social media a good thing?",
	"Is the thumb a finger?",
	"What is a \"guilty pleasure\" you've decided to stop feeling guilty about?",
	"What is the difference between happiness and contentment?",
	"Is there a person you'd like to meet one day?",
	"Is there a romantic moment you still keep in your heart, even if it wasn't meant to be?",
	"What is a super basic thing you've never learned how to do?",
	"Is there a version of yourself you secretly hope to become?",
	"What is one trend you'd like to bring back?",
	"Is there someone here you'd like to give a hug?",
	"Is there something you believe in that doesn't have a logical explanation?",
	"Is water wet? What about lava?",
	"Make a wish.",
	"Name a thing everyone seems to like, but you don't.",
	"Say something that you like about yourself.",
	"The perfect crime?",
	"What can be found under your bed?",
	"What circumstances could make you blush a little?",
	"What conspiracy theory would you start just to confuse people? ",
	"What do you feel like you are missing the most right now?",
	"What do you put first into the bowl: milk or cereal?",
	"What does your most-used emoji say about you?",
	"What everyday object do you think is secretly judging you?",
	"What features would you wish to be implemented into VRChat one day?",
	"What if every person could see each other's thoughts? How would human society change?",
	"If you woke up tomorrow with no memory of who you are, what clues would you look for to figure yourself out?",
	"What is a subject you liked at school? What's one you hated?",
	"What is more important to you: feeling secure of feeling free?",
	"What is one of your most precious memories?",
	"What is something funny or interesting that happened to you while traveling?",
	"What is something in your room that could give hint about what kind of person you are?",
	"What is something you currently procrastinate on doing?",
	"What is something you'd like to create for VRChat that you haven't created yet?",
	"What is the most beautiful lie that people tell themselves?",
	"What is the most unusual/unexpected thing that can be found on your desk?",
	"What is your favorite dessert?",
	"What is your favorite kind of VRChat world?",
	"What is your most played game on Steam other than VRChat?",
	"What is your sleep cycle like?",
	"What kind of compliment means the most to you?",
	"What kind of movies/series did you like to watch when you were a child?",
	"What kind of text messages annoy you?",
	"What kind of VRChat player are you?",
	"What made you choose your avatar?",
	"What makes you happy?",
	"What part of yourself do you think people notice first, and what part do you wish they noticed?",
	"What scent would your happy place smell like?",
	"What was one of the first videos you saw on the internet?",
	"What was your dream job when you were a child?",
	"What would be your weapon of choice during a zombie apocalypse?",
	"What's a \"green flag\" about yourself?",
	"What's a \"rule\" you live by, and where did it come from? Is it still serving you?",
	"What's a belief you held deeply that you've since changed your mind about?",
	"What's a childhood belief you held onto way too long?",
	"What's a chore or task that you secretly enjoy doing? What's something you tend to avoid?",
	"What's a color you'd happily paint a whole room",
	"What's a dumb/awkward thing you've done as a child?",
	"What's a fictional world you think you'd thrive in?",
	"What's a food, smell, or music that makes you feel instantly nostalgic?",
	"What's a kind of intimacy you crave that doesn't involve touch?",
	"What's a lie you've told to get out of an uncomfortable situation?",
	"What's a little luxury you like to treat yourself to?",
	"What's a memory you revisit when you need to feel grounded?",
	"What's a moment in your life that felt like a turning point?",
	"What's a moment in your life that would make a good movie scene?",
	"What's a movie you'll defend forever, no matter how bad people say it is?",
	"What's a part of your personality that you often try to hide?",
	"What's a piece of clothing you've worn overly much?",
	"What's a quality you admire in others?",
	"What's a question that you think we should be asking but aren't?",
	"What's a random deep-dive internet rabbit hole you've recently found yourself in?",
	"What's a skill you've always wanted to learn, and what holds you back from starting it?",
	"What's a small, oddly specific thing that makes your day 10x better?",
	"What's a snack you never get tired of?",
	"What's a sound or smell that always evokes a strong emotion in you?",
	"What's a sound that you find oddly comforting?",
	"What's a tiny tradition or routine that makes your day feel right?",
	"What's a truth you've accepted, even if it still stings a little?",
	"What's a weird thing your reflection has seen you do?",
	"What's an unexpected compliment you've gotten in the past?",
	"What's more attractive to you: someone who challenges you or someone who comforts you?",
	"What's one of the weirdest encounters you've had in VRChat so far?",
	"What's something simple you always look forward to?",
	"What's something small someone could do that would instantly make you feel cared for?",
	"What's something small that always makes you smile, no matter what?",
	"What's something that makes you feel safe around someone?",
	"What's something totally normal that you irrationally hate doing?",
	"What's something totally normal that, for some reason, creeps you out?",
	"What's something you always notice first when you meet someone new?",
	"What's something you end up doing when no one's watching?",
	"What's something you miss that you didn't realize was special until it was gone?",
	"What's something you own that has zero monetary value but a lot of meaning?",
	"What's something you're surprisingly picky about?",
	"What's something you've outgrown, but still sometimes miss?",
	"What's the most significant risk you've taken?",
	"What's the weirdest dream you've ever had or,a weird dream you've recently had? ",
	"What's your favorite way to connect with someone? Like talking or doing something together?",
	"What's your favorite way to spend a lazy afternoon?",
	"What's your favorite way to wind down after a long day?",
	"What's your go-to move when you need to cheer yourself up?",
	"What's your idea of a perfect \"slow day\" with someone you really like?",
	"What's your ideal way to start the day if there were no obligations?",
	"What's your most oddly specific favorite smell?",
	"What's your opinion on tattoos? Do you have any?",
	"What's your strategy for surviving a sudden zombie outbreak?",
	"What's your ultimate comfort food?",
	"When do you feel most at peace?",
	"When do you feel most yourself? How often do you get to be that version of you?",
	"When's the last time you felt seen in a way that surprised you?",
	"What everyday object do you suspect has a secret personality and what's its vibe?",
	"Who would you like to have with you if you were stranded on a desert island?",
	"Would you like time travel to exist?",
	"Would you mind living in a simulation?",
	"Would you rather always feel well-rested or always feel like you're in good company?",
	"Would you rather always find the perfect playlist for your mood or always stumble upon the coziest corner to sit?",
	"Would you rather always have the perfect words to express how you feel or always know just what someone else needs to hear?",
	"Would you rather always have to communicate with singing, whispering, or shouting?",
	"Would you rather always have to enter a room with a dance move or leave with a dramatic performance?",
	"Would you rather always have vivid dreams that feel amazing or fall asleep the moment your head hits the pillow?",
	"Would you rather always start your day with your favorite breakfast or always end it with your favorite dessert?",
	"Would you rather be constantly challenged, or always comfortable but bored?",
	"Would you rather be deeply understood by one person or generally liked by everyone?",
	"Would you rather be known for doing one thing exceptionally well, or for being pretty good at everything?",
	"Would you rather be known for making people feel seen or making people feel safe?",
	"Would you rather be known for something you didn't do, or never be recognized for something you did?",
	"Would you rather be known for your creativity or your kindness?",
	"Would you rather be really great at making people laugh or really great at making them feel calm?",
	"Would you rather be the funniest person in the room or the most respected?",
	"Would you rather be wildly successful at something you don't care about or struggle with something you deeply love?",
	"Would you rather collaborate with someone you admire but clash with, or someone you're completely in sync with but less inspired by?",
	"Would you rather create something deeply personal that no one understands, or something wildly popular that doesn't reflect you at all?",
	"Would you rather fart every time someone says your name or burp every time you say someone else's?",
	"Would you rather go on a slow, scenic train ride or get lost in a comfy, quiet bookstore for hours?",
	"Would you rather have a fridge that restocks with random snacks daily or a closet that generates one new mystery outfit per week?",
	"Would you rather have a home full of cozy corners or windows with beautiful views?",
	"Would you rather have a voice that instantly makes people feel calm, or a laugh that always spreads joy?",
	"Would you rather have endless ideas but never finish them, or complete everything you start but never feel fully inspired?",
	"Would you rather have endless time but limited energy, or endless energy, but limited time?",
	"Would you rather have one extra day each week with zero responsibilities or two extra hours every evening just for yourself?",
	"Would you rather have to take cold showers every day or give a 5-minute speech about a randomly chosen topic every week?",
	"Would you rather know how you're going to die or when you're going to die?",
	"Would you rather live in a home that's always filled with natural sunlight or one that's perfectly cozy on rainy days?",
	"Would you rather lose all your memories up to this point or never be able to make new ones?",
	"Would you rather lose your favorite creative outlet forever or have to share everything you make with the world, no matter what?",
	"Would you rather make something that changes one person's life or mildly entertains millions?",
	"Would you rather never feel awkward again, or be totally okay with feeling awkward?",
	"Would you rather relive one beautiful moment from your past or skip ahead and see one beautiful moment to look forward to?",
	"Would you rather sneeze confetti or hiccup tiny bubbles?",
	"Would you rather spend a weekend in a quiet cabin surrounded by mountains and nature or in a small seaside town?",
	"Would you rather spend a year living your dream life with no memory of it afterwards, or live an ordinary life you'll always remember?",
	"Would you rather spend your free time learning a new hobby or revisiting something that used to make you happy?",
	"Would you rather travel your whole life, or always stay at home?",
	"Would you recommend VRChat to a friend?",
	"Would you take a guarantee to get exactly 100 years old?",
	"Would you want someone to truly, attentively listen to you, but without getting a verbal response?",
	"Would you want to live forever if you could?",
	"You can talk to plants now, but they're passive-aggressively honest. What do they say about your life choices?",
	"You gain the ability to summon one mildly inconvenient thing anytime, anywhere. What do you choose?",
	"You have 2 fuses that take exactly 1 hour to burn, but they don't burn at a steady rate. How to measure 45 minutes with them?",
	"You meet someone with your exact same weird habits. Are you soulmates or rivals?",
	"What is your best moment today so far?",
	"Your favorite stuffed animal from childhood comes to life. What do you think would be the first thing it says to you?",
	"What is your favorite thing to do in VR?",
	"Do think there is life on another planet out there?",
	
	//Mr. Rodgers
	"What do you do with the mad that you feel?",
	"Who are the people who have helped you become who you are?",
	"Have you ever felt so proud you could burst?",
	"What makes you feel proud of yourself?",
	"What do you do when you're feeling lonely?",
	"How do you show someone you love them?",
	"What do you think about when you're quiet?",
	"When is the last time you felt truly safe?",
	"Who do you trust to share your feelings with?",
	"What is something special about you that no one else has?",
	"Who has loved you into being?",
	"Think about someone who encouraged you.",
	"What kind of neighbor are you?",
	"How are you helping others?",
	"What is essential, but invisible to the eye?",
	"How do you care for your own soul?",
	"What does it mean to be a helper?",
	"What is the most important thing to you right now?",
	"How do you express your feelings safely?",
	"What hopes do you have for yourself?",
	"When have you felt the deepest sense of belonging?",
	"What is your gift to the world?",
	"How do you find the courage to be yourself?",
	"Who have you thanked today?",
	"When did you last feel understood?",
	"What song is singing inside you today?",
	"When you think about the people who have helped you most in your life, what qualities do they have that you admire most?",
	"When you’re feeling sad or overwhelmed, who or what do you turn to for comfort, and how does it help you?",
	"Can you think of a time when someone really listened to you — really, truly listened — and how that made you feel inside?",
	"What parts of yourself are you proudest of, even if nobody else ever sees them?",
	"When was a time you were scared, and what helped you feel safe again?",
	"In what ways are you already the person you’ve always hoped to become?",
	"What memories give you strength when you're feeling uncertain about yourself?",
	"If you could say something to the child you once were, what would you most want that child to know?",
	"Have you ever done something difficult, something you didn’t think you could do, and how did you find the courage to do it?",
	"When you think about what it means to be truly kind, what small, everyday things come to mind?",
	"Is there someone you’ve lost touch with but still carry with you in your heart? How have they shaped who you are today?",
	"What does it mean to you to belong — not just to a place, but to a group, or to a feeling of home?",
	"When you look back on your hardest days, what surprising sources of hope did you discover?",
	"What would it feel like to give yourself the same patience and compassion that you so willingly offer to others?",
	"What are the ways you show love without using any words at all?",
	"How do you care for your invisible needs — your need for rest, kindness, respect, and peace?",
	"When you think about the parts of yourself you sometimes hide, what would it take for you to feel safe enough to share them?",
	"Have you ever forgiven yourself for something you thought you never could? What did that forgiveness feel like?",
	"Is there a hope you once had that you’ve quietly carried with you, even when the world made it hard to believe in it?",
	"What do you most long for others to understand about you, even if you’ve never found the right words to say it?",
	"When you are alone with your thoughts, which memories visit you most often — and what do they want to teach you?",
	"What parts of your story do you still find yourself wrestling with — and can you offer those parts patience instead of judgment?",
	"When you remember someone you’ve lost, what part of their spirit do you find living quietly inside you now?",
	"If you could lay down all the burdens you carry for just a little while, what might you discover about the person beneath them?",
	"In what ways have you already survived more than you once thought you could?",
	"When was a time you felt truly seen — not for what you could do, but simply for who you are?",
	"What would it be like to believe, even for a moment, that you are enough just as you are, without needing to earn it?",
	"What are the small, tender things you do each day that no one else sees — and how might they be acts of great courage?",
	"What would you tell someone younger than you, who feels afraid they will never be understood?",
	"Is there a part of you still waiting to be welcomed home with love?",
	"How would it change the way you move through the world if you treated every part of yourself — even the hurting parts — with gentleness?",
	"When was the last time you allowed yourself to hope for something beautiful without demanding a guarantee that it would happen?",
	"If your emotions were colors, what would your heart look like today?",
	"What is a secret dream you carry that you’ve never spoken aloud?",
	"If you could give your younger self a gift, what would you place carefully in their hands?",
	"Where in your life do you feel most like you are planting seeds, even if you can’t see anything growing yet?",
	"Is there a sound, a scent, or a feeling that instantly brings you back to a place where you felt safe?",
	"If your kindness could take a visible shape, what do you imagine it would look like?",
	"What are the invisible things you’re working hard at every day, even if no one else notices?",
	"If your life had a theme song right now, what would it be singing about you?",
	"When was a time you said 'yes' to something that scared you — and what did it teach you about trust?",
	"What is one place inside you that you’re still learning how to love?",
	"What does it feel like when someone believes in you — and how do you offer that same belief to others?",
	"If you could speak to a fear you carry, what would you want to say to it?",
	"What is something beautiful you learned from someone you once misunderstood?",
	"In what ways has your idea of 'strength' changed as you’ve grown older?",
	"What is a part of yourself you’ve reclaimed after thinking it was lost?",
	"If your soul could leave a note on your pillow tonight, what do you think it would want to tell you?",
	"What are the 'ordinary' moments in your life that might actually be sacred?",
	"Where have you been brave without even realizing it?",
	"If you could hold a conversation with your future self, what question would you most want to ask them?",
	"What are the promises you make silently to yourself each day?",
	"When you close your eyes and remember a happy time, what small details come back to you first?",
	"Is there a memory you hold close because it reminds you who you really are?",
	"What forgotten smell or sound would you give anything to experience one more time?",
	"Can you think of a day from your past that still feels unfinished in your heart?",
	"What memory feels as soft as a worn-in sweater, something you reach for when you need comfort?",
	"Is there a song that carries a piece of your childhood in its melody?",
	"When you think of a place you loved long ago, what is the very first thing you see?",
	"Have you ever found an old photograph that made you remember a part of yourself you'd almost forgotten?",
	"What memory still feels too fragile to hold for very long, like a bubble that might burst?",
	"If your memories were a garden, which moments would you plant again, and which ones would you let grow wild?",
	"Is there a time you remember differently now than you did when you were living it?",
	"What memory smells like home to you?",
	"Who is someone whose memory lives inside you almost like a light you carry around?",
	"Have you ever touched something — a rock, a toy, a piece of clothing — that instantly transported you to another time?",
	"What memory is stitched into the corners of your heart, even if no one else would recognize its importance?",
	"Is there a season of your life that feels wrapped in a particular color, a kind of emotional weather?",
	"When you think of a memory you cherish, what feelings rise up that are hard to put into words?",
	"Have you ever stumbled across a memory by accident — and how did it change your day?",
	"Which memory do you think you will still carry with you, even when everything else fades away?",
	"If you could step back into one memory just for a moment, what would you hope to notice this time that you missed before?",

	
	//Eco's Mostly Original Questions
	"What was your earliest favorite movie and why?",
	"What class did you enjoy the most in school or college?",
	"If you had a million dollars, what would you do?",
	"What is a quote or popular reference you mention often?",
	"What would you say to someone who feels anxious right now?",
	"What would you say to someone who looks up to you and why?",
	"Do you have a hobby that few people get to see? If so, why?",
	"What was your earliest memory using a computer?",
	"What was the first video game you ever played?",
	"What would be the first thing you do tomorrow if you woke up as your current VRChat avatar?",
	"What would life be like if every VRChat user woke up tomorrow as their VRChat avatar?",
	"Do you ever dream about dragons? What do they look like?",
	"How would you describe \"real life\" to someone in your dreams?",
	"What question do you want someone to ask you right now?",
	"What would you plant in your ideal garden?",
	"List three important things that video games taught you.",
	"If your mind was a house, what would it look like?",
	"What \"social norms\" would you erase and why?",
	"Do you cook? Why or why not?",
	"What is one meal you are decently good at cooking?",
	"What was the last meal you cooked for yourself?",
	"What did you eat today?",
	"What is a habit you have but wish you didn't?",
	"What do you do for fun?",
	"What makes you laugh every time?",
	"What are three things you are curious about?",
	"what are three things you are passionate about?",
	"What kind of dreams do you enjoy the most?",
	"What is something you do that others may find annoying?",
	"What is your superpower?",
	"How did you first discover the fandom you are in?",
	"Whats a power you didn't ask for but is cool/useful sometimes?",
	"What is your favorite comic/webcomic and why?",
	"Are you a spontaneous person or do you plan your days thoughtfully?",
	"When was the last time you felt anxious and how did you overcome it?",
	"What topics are you most comfortable talking about?",
	"How do you like to get cozy?",
	"List three YouTubers you watch.",
	"This is not a question. Remember to stay hydrated! :>",
	"What makes a friend a BEST FRIEND?",
	"What is your earliest memory?",
	"What was the most recent thing you built?",
	"Do you enjoy cold or warm environments?",
	"List three things that are nostalgic to you.",
	"How do you learn a new skill?",
	"How do you typically approach a difficult topic or situation?",
	"What is something you wish more people understood about you?",
	"How would you describe the first half of your life?",
	"What were you up to half-your-life ago?",
	"What motivates you?",
	"What aspect of yourself are you most critical about?",
	"Do you know anyone in-person who is also part of your fandom or shares your same interests?",
	"What do you never cheap-out on?",
	"What purchase is worth every penny?",
	"What was the last thing you fixed?",
	"What drains you of energy? What fills you with energy?",
	"What tool do you think everyone needs?",
	"What game most defines you today?",
	"Describe the weather outside right now.",
	"How do you meet new friends?",
	"Do you ever give random complements to strangers? Why or why not?",
	"What advice do you have for someone that wants to make more friends?",
	"What advice do you have for someone that looks up to you?",
	"What is your favorite game genre?",
	"How do you introduce yourself to someone new?",
	"How do you introduce a new friend to your other friends?",
	"You are given a magic dragon. What are your three wishes?",
	"What is something that bothers you but you can't change?",
	"What else are you doing tonight?",
	"Are you more of an empathetic or sympathetic person?",
	"What animal or creature best defines you and why?",
	"What fear do you have that holds you back?",
	"Do you always think about what other people think about you?",
	"What are you a born natural at?",
	"Do you keep a Journal?",
	"What is something you told yourself you'd do tomorrow?",
	"When given a task or assignment, do you do it ASAP or wait until the last minute?",
	"If your best friend disappeared for a week, would you be alarmed?",
	"How are you?",
	"What do you want more of?",
	"What was the last thing you drew/sketched?",
	"When was the last time you vibed with someone?",
	"When looking for a partner, are you more romantically attracted, intimately attracted, both, or neither?",
	"Do you love learning new things?",
	"What is something you wanted to say earlier, but never got the chance to?",
	"What is something about yourself that you are proud of?",
	"Do you live in the moment or dwell in the past?",
	"Whats on your mind right now?",
	"What do you dedicate the most time toward?",
	"What would you be if not a human?",
	"What color is your room?",
	"What did you want to be as a kid? what are you now?",
	"Do you ever play devils advocate with someone you otherwise agree with?",
	"Which one of your friends have you known the longest? How did you first meet?",
	"If you were a dragon, what would you look like?",
	"If you could go anywhere in the world, where would you go?",
	"If traveling across the world was as simple as a hop, skip, and jump, where would you go?",
	"If you woke up as your main OC or avatar IRL tomorrow, who would be the first person you tell?",
	"If you had wings, but couldn't fly, what else would you use your wings for?",
	"If you could invite anyone over right now, who would it be?",
	"\"Wake up, you're dreaming.\" Where would you wake up?",
	"What was the last thing you debated getting, but talked yourself out of?",
	"What was the last risk you took?",
	"What is your favorite food to cook?",
	"What do you like about yourself?",
	"What do you like about the person closest to you?",
	"After you meet someone for the first time, what things do you tend to remember about them?",
	"Do you have a 3D printer? What was the last thing you printed on it?",
	"What is something you wish you can change about yourself?",
	"What do you think life was like in the year that you were born?",
	"What was your dream job as a child?",
	"Do you have any pet peeves?",
	"What is on your mind right now?",
	"What is your favorite kind of store?",
	"Where were you half your life ago?",
	"What book have you read that stuck with you?",
	"What is something you wish to do more of?",
	"What is something or some place you like to explore?",
	"Whats the last piece of music you listened to?",
	"What kind of games do you like to play?",
	"What is something you worked hard on but not many people noticed?",
	"What did you do today?",
	"What meme is on your mind right now?",
	"List three things you can hear right now.",
	"What is something you take for granted?",
	"What is your \"million dollar idea?\"",
	"Who was your most favorite teacher in school?",
	"What was one of your old nicknames?",
	"What is a strange food combination you enjoy?",
	"What strange food combination do you not understand?",
	"What are three oddities about yourself?",
	"What things make you feel uncomfortable?",
	"What’s your zodiac sign, and does it resonate with you?",
	"How would you improve your current living space right now, if you could?",
	"What is a hobby would you like to pick up?",
	"What do you collect/hoard?",
	"What is something you are thankful for?",
	"What is something you need more of in your life right now?",
	"If you could change one thing about the world, what would it be?",
	"How do YOU pronounce \"Oatmeal?\"",

	"What kind of videos do you like to watch",
	"What made you choose your username and why?",
	"What is something about your body that you take for granted?",
	"Do you believe in hate? Why?",
	"What is a TV show you used to love watching, but no longer airs? ",
	"What hobbies do you have?",
	"What is something you have recently grown tolerant of?",
	"Can you do any funny voices?",
	"What is your favorite VRChat group that you are in?",
	"What is something you wish your friend groups did more of?",
	"Have you ever had a vivid dream you couldn't possibly explain?",
	"Do you ever have reoccurring dreams?",
	"What is your favorite US State?",
	"What is your favorite European country?",
	"How would you describe your mood right now?",
	"What was your first experience like in a library?",
	"Are you good at teaching people? If so, what would you teach?",
	"In your friend group, who is most likely to save you?",
	"What do you think your family was up to in the 1800s?",
	"Do you consider yourself stoic?",
	"Do you curse a lot? Why?",
	"What would be the most delicious food and drink spread you could eat right now?",
	"Do you prefer white, milk or dark chocolate?",
	"Are you good at acting?",
	"What could you go on about for hours?",
	"Why do you think animals dream?",
	"What is the most trouble you got in while time traveling?",

	"Did you hug your best friend today?",
	"When do you know it's time for a PC upgrade?",
	"Can you dance?",

	"How does you in VRChat differ from you in real life? How are they similar?",
	"What would the world be like if everyone had access to a character editor screen?",
	"What would you do if your VRChat avatar spawned in beside you one morning IRL?",
	"How do you communicate without words?",
	"What does your mind's voice sound like?",
	"If you woke up as your ideal self tomorrow, what would change?",
	"What was the last thing you focused on?",
	"What makes you smile?",
	"How do you make others smile?",
	"Can you make someone smile on command?",
	"Do you ever daydream about other worlds?",
	"What do you think is more important, Physics or Philosophy?",
	"What kind of car do you drive? (if any)",
	"Why did you get into VRChat?",
	"What aspect about you do you think would surprise most others?",
	"What kind of potato is best?",
	"How do you deal with something you don't understand?",
	"Do you play any instruments?",
	"What was the last thing you took a photo of?",
	"What kind of food can you like unregrettably eat forever?",
	"Describe your most recent dream.",
	"Do you meditate? If so, what is your method?",
	"How did you first get into your main hobby or passion?",
	"What is something important to you that is very hard to communicate.",
	"What would life be like if sleep was not required?",
	"Describe the last experience of deja vu you had.",
	"What does regret mean to you?",
	"What was the last piece of music you remember listening to?",
	"What rare/special item would you drop if you were a character in a video game?",
	"What gift can someone give you to increase your friendship level?",
	"What is a subject that makes you excited?",
	"What are your preferred pizza styles and toppings?",
	"If you're a cereal, what kind of cereal would you be?",
	"Tell a campfire story.",
	"What is one thing or problem you refuse to fix?",
	"If horses had a voice, what do you think they would sound like?",
	"Growing up, how was your relationship with the fundamentals of conscious existence?",
	"If you were a plant, what kind of plant would you be?",
	"What is your favorite sandwich?",
	"Would you rather only be able to transform yourself into anyhting you wanted, or only be able to transform others?"
	
	
	// More to be added. Don't forget final array comma!

//};  //Udon placeholder for VRChat world, Eco's Alcove.
];

var randArray = [];
let currentIndex = -1;

let inactivityTimer; // Timer for inactivity

const randomString = document.getElementById('randomString');
const dbg = document.getElementById('dbg');

function updateDisplay() {
  if (currentIndex >= 0 && currentIndex < randArray.length) {
    randomString.textContent = randArray[currentIndex];
    dbg.textContent = currentIndex + " / " + strings.length;
  } else {
    randomString.textContent = "←Click | Click→";
  }
}

function pickRandomUniqueString() {
  const availableStrings = strings.filter(str => !randArray.includes(str));
  if (availableStrings.length === 0) {
	randArray = [];
	currentIndex = 0;
    return "That was all the questions!";
  }
  const randomIndex = Math.floor(Math.random() * availableStrings.length);
  return availableStrings[randomIndex];
}

function handleRightSideClick() {
  currentIndex++;
  if (currentIndex >= randArray.length) {
    const randomStr = pickRandomUniqueString();
    if (randArray.length <= strings.length) {
      randArray.push(randomStr);
    }
  }
  updateDisplay();
}

function handleLeftSideClick() {
  if (currentIndex > 0) {
    currentIndex--;
    updateDisplay();
  }
}

function resetInactivityTimer() {
  clearInterval(inactivityTimer);
  inactivityTimer = setInterval(() => {
    handleRightSideClick(); 
  }, 31000); 
}

document.addEventListener('click', (e) => {
  const clickX = e.clientX;
  const screenWidth = window.innerWidth;

  if (clickX < screenWidth / 2) {
    handleLeftSideClick();
  } else {
    handleRightSideClick();
  }
  resetInactivityTimer(); 
});

document.addEventListener('mousemove', () => {
  resetInactivityTimer(); 
});

document.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowLeft') {
    handleLeftSideClick();
    resetInactivityTimer();
  } else if (e.key === 'ArrowRight') {
    handleRightSideClick();
    resetInactivityTimer();
  }
});

// Initial display
updateDisplay();
resetInactivityTimer(); // Start inactivity timer on load
